[module]
  [[module.imports]]
    path = 'github.com/camachom/hugo-theme-nostyleplease'

[taxonomies]
  tag = "tags"
  series = "series"

baseURL = "https://me.vs.computer"
languageCode = "en-us"
theme = "hugo-theme-nostyleplease"

[params]
  customCSS = ["css/main.scss"]
  favicon = "favicon.ico"

  [params.chatbot]
    enabled = true
    apiUrl = "https://guardrail.5d2z4xvxvd.workers.dev/chat"

  [params.theme_config]
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true